name: customer_churn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - protobuf=3.13.0
  - qt=5.12
  - pytest=6.2.2
  - pip=20.3.3
  - pip:
      - scikit-learn==0.24.1
      - shap==0.40.0
      - joblib==1.0.1
      - pandas==1.2.4
      - numpy==1.20.1
      - matplotlib==3.3.4
      - seaborn==0.11.2
      - pylint==2.7.4
      - autopep8==1.5.6
      - ipython==7.16.0
